feat: generate JSON for arbitrary CBOR
blinklabs-io/gouroboros pull request #355
Opened 2023-06-30 19:39 UTC by agaffney

Fixes #305

2023-06-30 20:11 UTC, wolf31o2 requested changes
Also, create a test case and guard against the case mentioned by the GitHub code scanner (or an issue for a later PR is fine, too)

2023-06-30 20:11 UTC, wolf31o2 commented on cbor/value.go
> +			if tmpTag.Number >= 121 && tmpTag.Number <= 127 {
Document these magic numbers

2023-06-30 21:47 UTC, agaffney commented on cbor/value.go
> +			if tmpTag.Number >= 121 && tmpTag.Number <= 127 {
Comments added

2023-07-01 00:28 UTC, wolf31o2 approved these changes

2023-07-01 00:32 UTC, merged